- {MinimumRequiredVersion: 4.21.0}
- arcturus
- gfx908
- [Device 7380, Device 7388, Device 738c, Device 7390]
- AllowNoFreeDims: false
  AssignedDerivedParameters: true
  Batched: false
  ComplexConjugateA: false
  ComplexConjugateB: false
  ComputeDataType: 0
  ConvolutionConfig:
  - {Dilation: 1x1}
  - {Filter: 1x1}
  - {Stride: 1x1}
  - {TensorAFormat: NCHW}
  DataType: 7
  DestDataType: 7
  HighPrecisionAccumulate: true
  Index0: 0
  Index01A: 0
  Index01B: 1
  Index1: 1
  IndexAssignmentsA: [0, 3, 2]
  IndexAssignmentsB: [1, 3, 2]
  IndexAssignmentsLD: [3, 4, 5, 6]
  IndexUnroll: 3
  IndexUnrollA: 1
  IndexUnrollB: 1
  IndicesBatch: [2]
  IndicesFree: [0, 1]
  IndicesSummation: [3]
  NumIndicesBatch: 1
  NumIndicesC: 3
  NumIndicesFree: 2
  NumIndicesLD: 0
  NumIndicesSummation: 1
  OperationType: ConvolutionBackwardData
  SetConstStrideA:
  - [0, 1]
  SetConstStrideB:
  - [1, 1]
  - [2, 0]
  SilentHighPrecisionAccumulate: false
  TLUA: true
  TLUB: true
  Tensor0: 0
  Tensor1: 1
  TileA: 0
  TileAwareSelection: false
  TileB: 1
  TotalIndices: 4
  TransposeA: false
  TransposeB: true
  UseBeta: false
  UseInitialStridesAB: false
  UseInitialStridesCD: false
  ZeroPadA: []
  ZeroPadB: []
- - 1LDSBuffer: 0
    AggressivePerfMode: 1
    AssertFree0ElementMultiple: 1
    AssertFree1ElementMultiple: 1
    AssertMinApproxSize: 3
    AssertSizeEqual: {}
    AssertStrideAEqual: {0: 1}
    AssertStrideBEqual: {0: 1, 2: 0}
    AssertStrideCEqual: {0: 1}
    AssertStrideDEqual: {0: 1}
    AssertSummationElementMultiple: 1
    AssignedDerivedParameters: true
    AssignedProblemIndependentDerivedParameters: true
    BufferLoad: true
    BufferStore: true
    CheckDimOverflow: 0
    CheckTensorDimAsserts: false
    CodeObjectVersion: V3
    DepthU: 32
    DirectToLds: false
    DirectToLdsA: false
    DirectToLdsB: false
    DisableAtomicFail: 0
    DisableKernelPieces: 0
    DisableVgprOverlapping: false
    EdgeType: ShiftPtr
    EnableMatrixInstruction: true
    ExpandPointerSwap: 1
    FractionalLoad: 1
    GlobalLoadVectorWidthA: 2
    GlobalLoadVectorWidthB: 2
    GlobalRead2A: true
    GlobalRead2B: true
    GlobalReadCoalesceGroupA: true
    GlobalReadCoalesceGroupB: true
    GlobalReadCoalesceVectorA: true
    GlobalReadCoalesceVectorB: true
    GlobalReadVectorWidth: 2
    GlobalSplitU: 1
    GlobalSplitUSummationAssignmentRoundRobin: true
    GlobalSplitUWorkGroupMappingRoundRobin: false
    GlobalWriteVectorWidth: 2
    GuaranteeNoPartialA: false
    GuaranteeNoPartialB: false
    ISA: [9, 0, 8]
    InnerUnroll: 1
    InterleaveAlpha: 0
    KernelLanguage: Assembly
    LSCA: 64
    LSCB: 64
    LSPA: 8
    LSPB: 8
    LVCA: 32
    LVCB: 32
    LVPA: 4
    LVPB: 4
    LdcEqualsLdd: true
    LdsBlockSizePerPad: 0
    LdsBlockSizePerPadA: 0
    LdsBlockSizePerPadB: 0
    LdsNumElements: 8192
    LdsNumElementsAlignedA: 2048
    LdsNumElementsAlignedB: 2048
    LdsOffsetA: 0
    LdsOffsetA_Blk: 4096
    LdsOffsetB: 2048
    LdsOffsetB_Blk: 6144
    LdsPadA: 0
    LdsPadB: 0
    LocalDotLayout: 1
    LocalRead2A: true
    LocalRead2B: true
    LocalReadVectorWidth: 2
    LocalSplitU: 1
    LocalWrite2A: true
    LocalWrite2B: true
    LocalWriteUseSgprA: false
    LocalWriteUseSgprB: false
    LoopDoWhile: false
    LoopIters: 4
    LoopTail: true
    LoopUnroll: 32
    MIBlock: [16, 16, 8, 1, 1, 1]
    MIOutputVectorWidth: 4
    MIWaveGroup: [2, 2]
    MIWaveTile: [2, 2]
    MacroTile0: 64
    MacroTile1: 64
    MacroTileA: 64
    MacroTileB: 64
    MacroTileShapeMax: 64
    MacroTileShapeMin: 1
    MagicDivAlg: 2
    MatrixInstB: 1
    MatrixInstBM: 1
    MatrixInstBN: 1
    MatrixInstK: 8
    MatrixInstM: 16
    MatrixInstN: 16
    MatrixInstruction: [16, 16, 8, 1]
    MaxOccupancy: 40
    MaxVgprNumber: 256
    MinVgprNumber: 0
    NonTemporalA: 0
    NonTemporalB: 0
    NonTemporalC: 0
    NumElementsPerThread: 16
    NumGlobalWriteVectorsPerThread: 8
    NumLoadsCoalescedA: 1
    NumLoadsCoalescedB: 1
    NumLoadsPerpendicularA: 4
    NumLoadsPerpendicularB: 4
    NumThreads: 256
    OptNoLoadLoop: 1
    PackBatchDims: 0
    PackFreeDims: 1
    PackGranularity: 2
    PackSummationDims: 0
    PackedC0IdxChars: [I]
    PackedC0IndicesX: [0]
    PackedC1IdxChars: [J]
    PackedC1IndicesX: [1]
    PerformanceSyncLocation: -1
    PerformanceWaitCount: -1
    PerformanceWaitLocation: -1
    PersistentKernel: 0
    PrefetchAcrossPersistent: 0
    PrefetchGlobalRead: 1
    PrefetchLocalRead: 1
    ProblemType:
      AllowNoFreeDims: false
      AssignedDerivedParameters: true
      Batched: false
      ComplexConjugateA: false
      ComplexConjugateB: false
      ComputeDataType: 0
      ConvolutionConfig:
      - {Dilation: 1x1}
      - {Filter: 1x1}
      - {Stride: 1x1}
      - {TensorAFormat: NCHW}
      DataType: 7
      DestDataType: 7
      HighPrecisionAccumulate: true
      Index0: 0
      Index01A: 0
      Index01B: 1
      Index1: 1
      IndexAssignmentsA: [0, 3, 2]
      IndexAssignmentsB: [1, 3, 2]
      IndexAssignmentsLD: [3, 4, 5, 6]
      IndexUnroll: 3
      IndexUnrollA: 1
      IndexUnrollB: 1
      IndicesBatch: [2]
      IndicesFree: [0, 1]
      IndicesSummation: [3]
      NumIndicesBatch: 1
      NumIndicesC: 3
      NumIndicesFree: 2
      NumIndicesLD: 0
      NumIndicesSummation: 1
      OperationType: ConvolutionBackwardData
      SetConstStrideA:
      - [0, 1]
      SetConstStrideB:
      - [1, 1]
      - [2, 0]
      SilentHighPrecisionAccumulate: false
      TLUA: true
      TLUB: true
      Tensor0: 0
      Tensor1: 1
      TileA: 0
      TileAwareSelection: false
      TileB: 1
      TotalIndices: 4
      TransposeA: false
      TransposeB: true
      UseBeta: false
      UseInitialStridesAB: false
      UseInitialStridesCD: false
      ZeroPadA: []
      ZeroPadB: []
    ReplacementKernel: false
    ScheduleGlobalRead: 1
    ScheduleIterAlg: 3
    ScheduleLocalWrite: 1
    SolutionIndex: 0
    SolutionNameMin: Cijk_Ailk_Bjlk_BH_MT64x64x32_MI16x16x8x1_SE_
    StaggerU: 0
    StaggerUMapping: 0
    StaggerUStride: 256
    StoreRemapVectorWidth: 4
    StoreVectorWidth: 4
    SubGroup0: 8
    SubGroup1: 32
    SubGroupA: 8
    SubGroupB: 32
    SuppressNoLoadLoop: 0
    ThreadTile: [2, 32]
    ThreadTile0: 8
    ThreadTile1: 2
    ThreadTileA: 8
    ThreadTileB: 2
    TransposeLDS: 0
    UnrollIncIsDepthU: 0
    UnrollMajorLDSA: 0
    UnrollMajorLDSB: 0
    UnrollMemFence: false
    Use64bShadowLimit: 1
    UseInstOffsetForGRO: 0
    UseSgprForGRO: -1
    Valid: true
    VectorAtomicWidth: 1
    VectorStore: -1
    VectorWidth: 2
    WaveSeparateGlobalReadA: 0
    WaveSeparateGlobalReadB: 0
    WorkGroup: [32, 8, 1]
    WorkGroupMapping: 1
    WorkGroupMappingType: B
    _UseSgprForGRO: false
    _VectorStore: 1
    _staggerStrideShift: 2
    fractionalPerpOverhangA: 0
    fractionalPerpOverhangB: 0
- [2, 3, 0, 1]
- - - [5329, 64, 64, 80]
    - [0, 16424.0]
- null
